export const categoriesSeedData = [
    {
        title: 'Red Dead Redemption 2',
        slug: 'red-dead-redemption-2',
        description: 'Red Dead Redemption 2 is a game about a cowboy who is trying to survive in the wild west. It is a sequel to Red Dead Redemption.',
        thumbnailUrl: 'categories/red-dead-redemption-2.webp',
    },
    {
        title: 'Grand Theft Auto V',
        slug: 'grand-theft-auto-v',
        description: 'Grand Theft Auto V is a game about a criminal who is trying to survive in the city. It is a sequel to Grand Theft Auto IV.',
        thumbnailUrl: 'categories/grand-theft-auto-v.webp',
    },
    {
        title: 'The Witcher 3: Wild Hunt',
        slug: 'the-witcher-3-wild-hunt',
        description: 'The Witcher 3: Wild Hunt is a game about a monster hunter who is trying to find his daughter. It is a sequel to The Witcher 2: Assassins of Kings.',
        thumbnailUrl: 'categories/the-witcher-3-wild-hunt.webp',
    },
    {
        title: 'The Last of Us',
        slug: 'the-last-of-us',
        description: 'The Last of Us is a game about a man who is trying to find his daughter. It is a sequel to The Last of Us.',
        thumbnailUrl: 'categories/the-last-of-us.webp',
    },
    {
        title: 'The Witcher 2: Assassins of Kings',
        slug: 'the-witcher-2-assassins-of-kings',
        description: 'The Witcher 2: Assassins of Kings is a game about a monster hunter who is trying to find his daughter. It is a sequel to The Witcher.',
        thumbnailUrl: 'categories/the-witcher-2-assassins-of-kings.webp',
    },
    {
        title: 'The Witcher',
        slug: 'the-witcher',
        description: 'The Witcher is a game about a monster hunter who is trying to find his daughter. It is a sequel to The Witcher 2: Assassins of Kings.',
        thumbnailUrl: 'categories/the-witcher.webp',
    },
    {
        title: 'GTA V',
        slug: 'gta-v',
        description: 'GTA V is a game about a criminal who is trying to survive in the city. It is a sequel to Grand Theft Auto IV.',
        thumbnailUrl: 'categories/gta-v.webp',
    },
    {
        title: 'Minecraft',
        slug: 'minecraft',
        description: 'Minecraft is a game about a man who is trying to find his daughter. It is a sequel to The Witcher 2: Assassins of Kings.',
        thumbnailUrl: 'categories/minecraft.webp',
    },
    {
        title: 'Fortnite',
        slug: 'fortnite',
        description: 'Fortnite is a game about a man who is trying to find his daughter. It is a sequel to The Witcher 2: Assassins of Kings.',
        thumbnailUrl: 'categories/fortnite.webp',
    },
    {
        title: 'League of Legends',
        slug: 'league-of-legends',
        description: 'League of Legends is a game about a man who is trying to find his daughter. It is a sequel to The Witcher 2: Assassins of Kings.',
        thumbnailUrl: 'categories/league-of-legends.webp',
    },
    {
        title: 'Valorant',
        slug: 'valorant',
        description: 'Valorant is a game about a man who is trying to find his daughter. It is a sequel to The Witcher 2: Assassins of Kings.',
        thumbnailUrl: 'categories/valorant.webp',
    },
    {
        title: 'Overwatch',
        slug: 'overwatch',
        description: 'Overwatch is a game about a man who is trying to find his daughter. It is a sequel to The Witcher 2: Assassins of Kings.',
        thumbnailUrl: 'categories/overwatch.webp',
    },
]

export const categoriesTopicsData = {
    'red-dead-redemption-2': [
        'Story Mode Walkthrough',
        'Online Multiplayer',
        'Horse Taming Guide',
        'Weapon Crafting',
        'Hunting & Fishing',
        'Gang Hideouts',
        'Treasure Hunting',
        'Bounty Hunting',
        'Poker & Gambling',
        'Wild West Survival'
    ],
    'grand-theft-auto-v': [
        'Story Mode Missions',
        'Online Heists',
        'Car Customization',
        'Business Management',
        'Racing Events',
        'Gang Wars',
        'Property Investment',
        'Weapon Arsenal',
        'Flying Lessons',
        'Underwater Exploration'
    ],
    'the-witcher-3-wild-hunt': [
        'Main Quest Walkthrough',
        'Side Quest Guide',
        'Monster Hunting',
        'Alchemy & Potions',
        'Gwent Card Game',
        'Witcher Gear Sets',
        'Romance Options',
        'Monster Contracts',
        'Treasure Hunts',
        'DLC Expansions'
    ],
    'the-last-of-us': [
        'Story Mode Complete',
        'Survival Horror Tips',
        'Crafting Guide',
        'Stealth Mechanics',
        'Weapon Upgrades',
        'Infected Enemies',
        'Multiplayer Factions',
        'Puzzle Solutions',
        'Collectibles Guide',
        'Left Behind DLC'
    ],
    'the-witcher-2-assassins-of-kings': [
        'Chapter Walkthrough',
        'Combat Techniques',
        'Alchemy System',
        'Political Choices',
        'Monster Contracts',
        'Character Development',
        'Magic & Signs',
        'Equipment Upgrades',
        'Romance Paths',
        'Multiple Endings'
    ],
    'the-witcher': [
        'Chapter Progression',
        'Combat Mechanics',
        'Alchemy Recipes',
        'Monster Bestiary',
        'Character Relationships',
        'Magic System',
        'Equipment Crafting',
        'Side Quests',
        'Romance Options',
        'Story Choices'
    ],
    'gta-v': [
        'Story Mode Complete',
        'Online Missions',
        'Vehicle Customization',
        'Property Management',
        'Heist Planning',
        'Gang Activities',
        'Racing Competitions',
        'Weapon Mastery',
        'Flying Skills',
        'Underwater Missions'
    ],
    'minecraft': [
        'Survival Mode',
        'Creative Building',
        'Redstone Engineering',
        'Mob Farming',
        'Resource Gathering',
        'Village Trading',
        'Nether Exploration',
        'End Dimension',
        'Modded Gameplay',
        'Multiplayer Servers'
    ],
    'fortnite': [
        'Battle Royale Tips',
        'Building Techniques',
        'Weapon Mastery',
        'Map Strategies',
        'Squad Tactics',
        'Creative Mode',
        'Save the World',
        'Tournament Play',
        'Skin Showcase',
        'Pro Strategies'
    ],
    'league-of-legends': [
        'Champion Mastery',
        'Lane Strategies',
        'Team Composition',
        'Jungle Pathing',
        'Objective Control',
        'Ranked Climbing',
        'Meta Analysis',
        'Pro Gameplay',
        'Champion Counters',
        'Team Fighting'
    ],
    'valorant': [
        'Agent Abilities',
        'Map Strategies',
        'Weapon Mastery',
        'Team Composition',
        'Spike Planting',
        'Defensive Setups',
        'Ranked Tips',
        'Pro Strategies',
        'Agent Counters',
        'Communication'
    ],
    'overwatch': [
        'Hero Mastery',
        'Team Composition',
        'Map Strategies',
        'Ultimate Combos',
        'Positioning Tips',
        'Ranked Play',
        'Pro Meta',
        'Hero Counters',
        'Communication',
        'Game Sense'
    ]
}