export const usernamesSeedData = [
    // Gaming & Tech
    'PixelWarrior',
    'CyberNinja',
    'QuantumGamer',
    'NeonStriker',
    'DigitalPhoenix',
    'ByteMaster',
    'CodeBreaker',
    'VirtualViper',
    'TechWizard',
    'GameOverlord',

    // Nature & Animals
    'ShadowWolf',
    'GoldenEagle',
    'CrimsonFox',
    'SilverLynx',
    'ThunderBear',
    'FrostTiger',
    'EmberDragon',
    'OceanWhisper',
    'ForestSpirit',
    'MountainPeak',

    // Fantasy & Mythology
    'DragonSlayer',
    'PhoenixRise',
    'Valkyrie',
    'ThunderGod',
    'MoonWalker',
    'StarChaser',
    'CrystalKnight',
    'ShadowMage',
    'LightBringer',
    'DarkHunter',

    // Colors & Elements
    'CrimsonBlade',
    'AzureStorm',
    'GoldenFlame',
    'SilverArrow',
    'EmeraldEye',
    'PurpleHaze',
    'BlackWidow',
    'WhiteKnight',
    'RedPhoenix',
    'BlueThunder',

    // Action & Power
    'IronFist',
    'SteelHeart',
    'FireStorm',
    'IceBreaker',
    'ThunderBolt',
    'LightningStrike',
    'WindWalker',
    'EarthShaker',
    'WaterBender',
    'AirMaster',

    // Cool & Edgy
    'NightStalker',
    'ShadowKiller',
    'DeathDealer',
    'BloodHunter',
    'SoulReaper',
    'DarkKnight',
    'VoidWalker',
    'ChaosBringer',
    'DoomSlayer',
    'HellRaiser',

    // Creative & Artistic
    'DreamWeaver',
    'ArtMaster',
    'CreativeSoul',
    'Visionary',
    'Imagination',
    'ColorSplash',
    'BrushStroke',
    'CanvasKing',
    'PaletteMaster',
    'DesignGuru',

    // Music & Rhythm
    'BeatMaster',
    'RhythmKing',
    'MelodyMaker',
    'SoundWave',
    'BassDropper',
    'HarmonySeeker',
    'TempoMaster',
    'GrooveLord',
    'VibeCreator',
    'AudioWizard',

    // Sports & Fitness
    'SpeedDemon',
    'PowerLifter',
    'EnduranceKing',
    'FlexMaster',
    'StrengthLord',
    'AgilityPro',
    'BalanceBeast',
    'StaminaStar',
    'MuscleMaster',
    'FitnessGuru',

    // Food & Cooking
    'ChefMaster',
    'SpiceKing',
    'FlavorLord',
    'TasteMaker',
    'CulinaryPro',
    'KitchenWizard',
    'RecipeMaster',
    'FoodArtist',
    'GourmetGuru',
    'CookingKing',

    // Travel & Adventure
    'Wanderer',
    'Explorer',
    'Adventurer',
    'Nomad',
    'Voyager',
    'Pioneer',
    'TrailBlazer',
    'PathFinder',
    'JourneyMan',
    'Wayfarer'
]